import { ThemeProvider } from 'next-themes';
import { Raleway } from 'next/font/google';
import { Roboto } from 'next/font/google';
import './globals.css';
import Header from "@/widgets/header/Header";

// Подключаем шрифты Raleway и Roboto
const raleway = Raleway({
    subsets: ['latin'],
    weight: ['400', '700'], // Например, обычный и жирный
});

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'], // Например, обычный и жирный
});

export const metadata = {
    title: 'LVGroup',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
            <head />
            <body
                className={`${raleway.className} ${roboto.className} antialiased`} // Применяем шрифты
            >
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <Header/>
                <main className={`flex flex-col items-center`}>
                    {children}
                </main>
            </ThemeProvider>
            </body>
            </html>
        </>
    );
}
